### ISSUE TITLE
Incorrect Height and Weight Data

### ISSUE THREAD

**Issue by lens0021** [patarapolw/squirdle#10]
Reported from the upstream: https://github.com/Fireblend/squirdle/issues/29

> The Height and Weight data for Mega Gardevoir, Origin Forme Dialga, and Origin Forme Palkia seem to be wrong.
> 
> Mega Gardevoir is listed as 3.3m/325kg and should be 1.6m/48.4kg, just like regular Gardevoir. Those values seem to be copied from Black Kyurem for some reason.
> 
> Dialga and Palkia Origin Formes are listed as the same as their base forms. According to the official Website of the game:
[Dialga is 7.0m/850.0kg](https://legends.pokemon.com/en-gb/pokemon/dialga/)
[Palkia is 6.3m/660.0kg](https://legends.pokemon.com/en-gb/pokemon/palkia/)

**Comment by patarapolw** [comment]
Not sure exactly which one should be fixed?

> name,generation,type_1,type_2,height_m,weight_kg,name_ja,name_ko
> ...
> Gardevoir,3,Psychic,Fairy,1.6,48.4,サーナイト,가디안
> Mega Gardevoir,6,Psychic,Fairy ~~,3.3,325~~ ,1.6,48.4,メガサーナイト,메가가디안
> ...
> Dialga,4,Steel,Dragon ~~,5.4,683.0~~ ,7.0,850.0,ディアルガ,디아루가
> Dialga Origin Forme,8,Steel,Dragon ~~,5.4,683.0~~ ,7.0,850.0,ディアルガ オリジンフォルム,디아루가 오리진폼
> Palkia,4,Water,Dragon ~~,4.2,336.0~~ ,6.3,660.0,パルキア,펄기아
> Palkia Origin Forme,8,Water,Dragon ~~,4.2,336.0~~ ,6.3,660.0,パルキア オリジンフォルム,펄기아 오리진폼
> ...

**Comment by patarapolw** [comment]
This should now be fixed as well (at `53476ac`).

**Comment by patarapolw** [comment]
I am not sure if there is a Pokemon API I can use for this, not only for weight and height, but also names, so that I can keep up with the official stats. (So that I don't have to maintain `pokedex.csv`)

https://pokeapi.co is a good one, but at least, it doesn't have Japanese Pokemon names.

> Dialga and Palkia Origin Formes are listed as the same as their base forms. According to the official Website of the game:
> [Dialga is 7.0m/850.0kg](https://legends.pokemon.com/en-gb/pokemon/dialga/)
> [Palkia is 6.3m/660.0kg](https://legends.pokemon.com/en-gb/pokemon/palkia/)

Actually, the URL of `en-gb` link is misleading. [パルキア](https://zukan.pokemon.co.jp/detail/484) vs [パルキアオリジンフォルム](https://zukan.pokemon.co.jp/detail/484-1). I have overfixed. Reverted in https://github.com/patarapolw/squirdle/commit/018f0e386c6c2ab7c9bcc33fb55113749ce3eff1.
